In [7]:
from functools import lru_cache
from typing import Dict, Any
import unicodedata

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
# import re
from rapidfuzz import process, fuzz
from sentence_transformers import SentenceTransformer


%matplotlib inline

# Dataframe loading

In [17]:
df_prod = pd.read_csv('data/20250501-carrefour_prods.csv', parse_dates=['dateKey'])
df_loyalty = pd.read_csv('data/20250501-carrefour_loyalty.csv', parse_dates=['date'])
df_prod['totalPriceAfterDiscount'] = df_prod['totalPrice'] + df_prod['totalImmediateDiscount']
display(df_prod)
display(df_loyalty)

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,2,0.000,2.39,4.78,-1.43,3.35
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,1,1.912,6.50,12.43,0.00,12.43
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,1,0.000,5.39,5.39,0.00,5.39
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,1,0.000,4.99,4.99,0.00,4.99
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,1,0.000,2.45,2.45,0.00,2.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,NaN,10.0,1,0.000,1.75,1.75,0.00,1.75
5015,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,NaN,5.5,1,0.000,2.50,2.50,0.00,2.50
5016,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,NaN,5.5,1,0.000,1.99,1.99,0.00,1.99
5017,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,NaN,5.5,1,0.000,0.61,0.61,0.00,0.61
5018,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,NaN,5.5,2,0.000,1.59,3.18,0.00,3.18

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels

In [18]:
mapped_categories = {
    'Charcuterie' : 'food', 
    'Laits et Boissons végétales' : 'food',
    'Jus de fruits et légumes': 'food', 
    'Toasts et Pains de mie': 'food',
    'Yaourts et Fromages blancs': 'food',
    'Conserves et Bocaux': 'food',
    'Colas, Thés glacés, Sirops et Sodas': 'food',
    'Légumes': 'food',
    'Huiles, Vinaigres et Vinaigrettes': 'food',
    'Nettoyants vaisselle' : 'other',
    'Accessoires de ménage' : 'other',
    'Matériel de bureau' : 'other',
    'Fromages': 'food',
    'Epicerie salée': 'food',
    'Cheveux' : 'other',
    'Pains Burger, Sandwich et Wraps': 'food',
    'Eaux': 'food',
    'Viandes': 'food',
    'Lessives' : 'other',
    'Pizzas, Quiches et Tartes': 'food',
    'Apéritifs et Chips': 'food',
    'Fruits': 'food', 
    'Volaille et Rôtisserie': 'food',
    'Glaces et Sorbets': 'food',
    'Bio à Petit prix': 'food',
    'Gâteaux moelleux': 'food',
    'Apéritifs, Entrées et Snacking': 'food', 
    'Petit déjeuner': 'food',
    'Hygiène dentaire' : 'other', 
    'Cave à Vins': 'food',
    'Boucherie': 'food',
    'Poissons et Fruits de mer': 'food',
    'Œufs': 'food',
    'Poissonnerie': 'food',
    'Essuie-tout, Papier toilette et Mouchoirs' : 'other',
    'Confiseries et Chocolats': 'food', 
    'RETURNABLE_BAG' : 'other', 
    'Hygiène intime ' : 'other',
    'Désodorisants et Bougies' : 'other',
    'Toutes nos régions': 'food',
    'Produits nettoyants' : 'other', 
    'Riz, Purées et Féculents' : 'food',
    'Ingrédients pour cuisiner' : 'food',
    'Sauces froides' : 'food',
    'Pains frais' : 'food',
    'Bières et Cidres' : 'food',
    'Repas de Pâques' : 'food',
    'Le Marché' : 'food',
    'Beurres et Crèmes' : 'food',
    'Premiers soins et Préservatifs' : 'other',
    'Nintendo Switch' : 'other',
    'Sucres, Farines et Aide à la pâtisserie' : 'food',
    'Viennoiseries et Brioches fraîches' : 'food', 
    'Corps' : 'other'
}

In [19]:
df_prod.loc[df_prod.category.isna(), "category"] = df_prod.loc[df_prod.category.isna(), "subCategory"].map(mapped_categories)

In [20]:
def input_from_csv(
    df: pd.DataFrame,
    filepath: str,
    column_name: str,
):
    """In-place computation of embedding"""
    input_df = pd.read_csv(filepath)
    if isinstance(column_name, str):
        merged_df = pd.merge(df, input_df, on=column_name, how="left", suffixes=("_original", "_imputed"))
    else:
        raise ValueError("column_name should be a string")
    return merged_df

In [21]:
df_prod = input_from_csv(
    df_prod,
    filepath='data/20250502-carrefour_food_products_labels_most_2.csv',
    column_name='productLabel'
)

In [22]:
df_prod.query('productLabel.notna()')

,dateKey,recordType,countVisits,ean,cdbase,productLabel,slugProductLabel,category,subCategory_original,vatPercentage,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalPriceAfterDiscount,subCategory_imputed
0,2025-04-29,receipt,2,NaN,NaN,5X10 D FREEDENT ME,5X10 D FREEDENT ME,other,NaN,20.0,2,0.000,2.39,4.78,-1.43,3.35,NaN
1,2025-04-29,receipt,1,NaN,NaN,KG POULET FERMIER,KG POULET FERMIER,food,NaN,5.5,1,1.912,6.50,12.43,0.00,12.43,Volaille et Rôtisserie
2,2025-04-29,receipt,1,NaN,NaN,750G OMEGA 3 DX SH,750G OMEGA 3 DX SH,other,NaN,20.0,1,0.000,5.39,5.39,0.00,5.39,NaN
3,2025-04-29,receipt,1,NaN,NaN,3 RECH RUBAN MAGI,3 RECH RUBAN MAGI,other,NaN,20.0,1,0.000,4.99,4.99,0.00,4.99,NaN
4,2025-04-29,receipt,1,NaN,NaN,132G BISC.COCO SSA,132G BISC.COCO SSA,food,NaN,5.5,1,0.000,2.45,2.45,0.00,2.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,2022-04-25,receipt,1,NaN,NaN,COURGETTE P10.5 CM,COURGETTE P10.5 CM,other,NaN,10.0,1,0.000,1.75,1.75,0.00,1.75,NaN
5015,2022-04-25,receipt,1,NaN,NaN,POMME ARIANE,POMME ARIANE,food,NaN,5.5,1,0.000,2.50,2.50,0.00,2.50,NaN
5016,2022-04-25,receipt,1,NaN,NaN,PIECE ANANAS EXTRA,PIECE ANANAS EXTRA,food,NaN,5.5,1,0.000,1.99,1.99,0.00,1.99,Conserves et Bocaux
5017,2022-04-25,receipt,1,NaN,NaN,MENTHE FRAI,MENTHE FRAI,food,NaN,5.5,1,0.000,0.61,0.61,0.00,0.61,NaN
5018,2022-04-25,receipt,2,NaN,NaN,MADEL LONG RAISIN,MADEL LONG RAISIN,food,NaN,5.5,2,0.000,1.59,3.18,0.00,3.18,NaN

In [23]:
df_prod.to_csv('data/20250501-carrefour_products.csv', index=False)

# Group analysis

The method unstack allows to view the `groupby` results in a natural table. This is actually a pivot on the column by which one applies `groupby`. 
The `reset_index()` method actually returns it as a table with index as rows instead (no pivoting). One or another is useful.

In [9]:
df_loyalty[['itemLabel', 'date', 'loyaltyOperation', 'itemRd']].groupby(by=[df_loyalty.date.dt.year, 'itemLabel'], sort=True).sum(numeric_only=True).sort_values(by=['date', 'itemRd'], ascending = [False, False]).unstack(fill_value=0)

                                  itemRd                                 \
itemLabel 100G GRANA PADANO RAPE AOP CRF 125G MOZZARELLA BUFALA BIO CRF
date
2024                                0.00                           0.00
2025                                0.58                           0.77

                                                             \
itemLabel 125G MOZZARELLA VACHE 12X125G YAOURTS PAT LA LAIT
date
2024                       1.19                        0.00
2025                       0.00                        1.34

                                                                        \
itemLabel 16X125G BIF NATURE ACTIVIA OD 16X125G YRT FRUIT 0% CRF CLASS
date
2024                               1.35                           0.61
2025                               0.00                           0.00

                                                                 \
itemLabel 1KG COUSCOUS MOYEN CRF 1KG FARINE BLE FLUID T45 CRF C
date
2024                         0.3                           0.13
2025                         0.0                           0.00

                                                               ...  \
itemLabel 1KG FARINE BLE T45 CRF CLASSIC 1KG FILET POULET PLK  ...
date                                                           ...
2024                                0.13                 0.00  ...
2025                                0.00                 1.99  ...

                                                           \
itemLabel RICORE RECHARGE 290G RUBAN TRANSPT 550 19MMX33M
date
2024                      0.00                       1.93
2025                      3.24                       0.00

                                                       \
itemLabel SALADE BATAVIA PIECE ST 1,5KG POMME GALA FR
date
2024                      0.37                   0.64
2025                      0.00                   0.00

                                                                               \
itemLabel ST 200G HARICOT.MUNGO 0,99 ST 2PCES MAIS DOUX HF ST 400G EPINARD FR
date
2024                            0.15                   0.0                0.0
2025                            0.00                   0.9                0.5

                                                                    \
itemLabel ST 500G BETTERAV PRIM FQC AGRO ST 500G BETTERAVE FQC AGR
date
2024                                0.27                      0.25
2025                                0.00                      0.00


itemLabel SWITCH SET MARIO KART 8 PASS C
date
2024                                10.5
2025                                 0.0

[2 rows x 102 columns]

In [ ]:
grouped_loyalty_year = df_loyalty[['itemLabel', 'date', 'loyaltyOperation', 'itemRd']].groupby(by=[df_loyalty.date.dt.year, 'itemLabel'], sort=True).sum(numeric_only=True).sort_values(by=['date', 'itemRd'], ascending = [False, False]).reset_index()
display(grouped_loyalty_year.head(10))

In [ ]:
display(grouped_loyalty_year[grouped_loyalty_year.date == 2024].nlargest(10, columns='itemRd'))

    date                       itemLabel  itemRd
58  2024  ART RAYON POISSONNERIE TVA 5,5   15.81
59  2024  SWITCH SET MARIO KART 8 PASS C   10.50
60  2024    ART RAYON FRUITS LEG TVA 5,5    9.84
61  2024      BANANE CRF BIO MH 5 FRUITS    9.09
62  2024             2X6TR 2X215G SF NOR    6.60
63  2024  2X75ML DENT PSA NETT INTENS OB    4.70
64  2024  2X75ML DENT S&G CALM ORIGIN OB    4.25
65  2024   2X75ML PSA GENC&EMAIL ORIG OB    4.24
66  2024   1X8L FF BP MATIN LEGER ECREME    4.08
67  2024   3X75ML DENT WN TP SENS SIGNAL    4.07

In [103]:
# Group by 'category' and sum the 'amount' column
spending_by_category = df_prod.groupby(['category', df_prod.dateKey.dt.year]).sum(numeric_only=True)

print("\nTotal Spending by Category:")
display(spending_by_category)

Total Spending by Category:

                  countVisits           ean       cdbase  vatPercentage  \
category dateKey
food     2022             947  0.000000e+00          0.0         4482.5
         2023            1620  0.000000e+00          0.0         7386.5
         2024            1745  6.645180e+14  781106656.0         7293.0
         2025             533  7.403638e+13  100131650.0         2370.5
other    2022             340  0.000000e+00          0.0         4660.0
         2023             476  0.000000e+00          0.0         6010.0
         2024             465  3.411904e+14  313664675.0         4640.0
         2025              88  6.492628e+13   55207784.0          960.0

                  totalQuantity  totalWeight    unitPrice  totalPrice  \
category dateKey
food     2022              1163       91.723  2559.725000     3046.18
         2023              1938      192.193  4475.635333     5454.36
         2024              2064      239.980  4858.790000     5683.34
         2025               614       98.519  1603.980000     1904.38
other    2022               331       -5.721  1519.430000     1763.48
         2023               474        0.000  2543.440000     3165.19
         2024               551       -1.200  1937.386667     2816.82
         2025               103        0.000   352.610000      609.50

                  totalImmediateDiscount  totalTruePrice
category dateKey
food     2022                    -133.34         2912.84
         2023                    -330.49         5123.87
         2024                    -165.56         5517.78
         2025                     -63.04         1841.34
other    2022                    -165.00         1598.48
         2023                    -382.10         2783.09
         2024                    -272.27         2544.55
         2025                     -41.68          567.82

In [ ]:
df_prod['yearMonth'] = df_prod.dateKey.dt.to_period('M')
# Group by year_month and product_id, then sum the quantities
grouped_month = df_prod.groupby(['yearMonth', 'productLabel']).agg(
    {'totalQuantity' : 'sum', 'totalWeight': 'sum', 'unitPrice' : 'mean', 'totalPrice' : 'sum', 'totalImmediateDiscount' : 'sum', 'totalTruePrice' : 'sum'}
).reset_index()

# Sort by year_month and quantity in descending order
sorted_grouped_month_quant = grouped_month.sort_values(by=['yearMonth', 'totalQuantity'], ascending=[True, False])
sorted_grouped_month_weight = grouped_month.sort_values(by=['yearMonth', 'totalWeight'], ascending=[True, False])

# Get the top 10 items for each month
top5_quant_by_month = sorted_grouped_month_quant.groupby('yearMonth').head(5)  # Top N records per group
top5_weight_by_month = sorted_grouped_month_weight.groupby('yearMonth').head(5)  # Top N records per group
display(top5_quant_by_month[top5_quant_by_month.yearMonth.dt.year == 2024])
display(top5_weight_by_month[top5_weight_by_month.yearMonth.dt.year == 2024])

,yearMonth,productLabel,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalTruePrice
2444,2024-01,KIWI JAUNE PIECE,20,0.000,0.723333,14.20,-2.32,11.88
2446,2024-01,KIWI VERT PIECE,12,0.000,0.640000,7.48,-1.88,5.60
2382,2024-01,24 PS EXTRA LONG C,9,0.000,1.550000,13.95,-1.24,12.71
2405,2024-01,6X1.5L CRISTALINE,9,0.000,1.140000,10.26,0.00,10.26
2445,2024-01,KIWI VERT FQC,8,0.000,0.690000,5.52,-1.52,4.00
2582,2024-02,KIWI VERT PIECE,17,0.000,0.590000,10.03,-1.74,8.29
2601,2024-02,Nettoyant Optique Dégraissant Anti Trace VU,8,0.000,2.790000,22.32,0.00,22.32
2536,2024-02,6X1.5L CRISTALINE,7,0.000,1.140000,7.98,0.00,7.98
2597,2024-02,Mouchoirs Confort CARREFOUR SOFT,6,0.000,3.790000,22.74,3.42,26.16
2568,2024-02,CITRON VERT PIECE,5,0.000,0.500000,2.50,-0.50,2.00
2738,2024-03,KIWI VERT PIECE,17,0.000,0.545000,9.31,-2.06,7.25
2671,2024-03,200G FRITUR MASS C,12,0.000,2.600000,31.20,-6.50,24.70
2702,2024-03,AVOCAT PIECE,4,0.000,1.440000,5.76,0.00,5.76
2706,2024-03,BATAVIA PIECE,4,0.000,0.990000,3.96,0.00,3.96
2721,2024-03,CONCOMBRE PIECE,4,0.000,1.190000,4.76,-0.76,4.00
2807,2024-04,ASSIETTE CREUSE 23,9,0.000,3.990000,35.91,-18.00,17.91
2849,2024-04,KIWI VERT PIECE,8,0.000,0.590000,4.72,-0.72,4.00
2836,2024-04,Eau minérale naturelle VITTEL,6,0.000,2.525000,15.15,5.05,20.20
2864,2024-04,PETIT VASE EN VERR,5,0.000,4.500000,22.50,-15.75,6.75
2887,2024-04,TOMATE CERISE ALL.,5,0.000,0.990000,4.95,0.00,4.95
2977,2024-05,KIWI VERT PIECE,21,0.000,0.590000,12.39,-0.72,11.67
3005,2024-05,PLANTE,6,0.000,2.990000,17.94,0.00,17.94
2912,2024-05,24 PS EXTRA LONG C,5,0.000,1.550000,7.75,0.00,7.75
2955,2024-05,CONCOMBRE PIECE,5,0.000,0.990000,4.85,-0.28,4.57
2992,2024-05,PAIN AUX RAISINSX1,5,0.000,0.750000,3.75,0.00,3.75
3046,2024-06,6X1.5L EAU AUV CRF,6,0.000,1.620000,9.72,-1.46,8.26
3072,2024-06,Eau minérale naturelle VITTEL,6,0.000,2.940000,17.64,5.88,23.52
3086,2024-06,MUG CONE 9 CM ROU,6,0.000,1.990000,11.94,0.00,11.94
3058,2024-06,Boisson végétale au soja nature Bio CARREFOUR BIO,4,0.000,1.190000,4.76,0.00,4.76
3081,2024-06,KIWI VERT FQC,4,0.000,0.590000,2.36,0.00,2.36
3180,2024-07,CHEM 3RBT POLYPRO,40,0.000,1.190000,47.60,0.00,47.60
3199,2024-07,KIWI VERT PIECE,22,0.000,0.590000,12.98,-1.80,11.18
3239,2024-07,X5 CHEM 3R CTE CRF,21,0.000,2.990000,62.79,0.00,62.79
3240,2024-07,X50 PPERF PP 50M C,10,0.000,1.890000,18.90,0.00,18.90
3142,2024-07,24 PS EXTRA LONG C,4,0.000,1.550000,6.20,-1.24,4.96
3329,2024-08,Kiwi jaune,18,0.000,0.990000,17.82,1.88,19.70
3327,2024-08,KIWI VERT PIECE,14,0.000,0.590000,8.26,-0.72,7.54
3376,2024-08,Protège-slip Extra Long CARREFOUR SOFT,14,0.000,1.450000,20.30,4.06,24.36
3374,2024-08,Pommes Pink Lady vrac,9,0.000,1.510000,13.59,0.00,13.59
3323,2024-08,INTER 12P A4 CL VI,8,0.000,1.690000,13.52,0.00,13.52
3511,2024-09,KIWI VERT PIECE,18,0.000,0.590000,10.62,-2.07,8.55
3513,2024-09,Kiwi jaune,12,0.000,0.990000,11.88,1.88,13.76
3473,2024-09,BQ TOM CERISE ALL,7,0.000,0.990000,6.93,0.00,6.93
3445,2024-09,5X10 D HLW MENTHE,6,0.000,2.790000,16.74,-4.19,12.55
3462,2024-09,AVOCAT PIECE,6,0.000,1.390000,8.34,-0.84,7.50
3633,2024-10,Kiwi jaune,12,0.000,0.990000,11.88,1.88,13.76
3610,2024-10,BQ TOM CERISE ALL,8,0.000,0.990000,7.92,0.00,7.92
3632,2024-10,KIWI VERT PIECE,8,0.000,0.590000,4.72,-0.72,4.00
3623,2024-10,Eau de source CARREFOUR CLASSIC',6,0.000,1.620000,9.72,0.96,10.68
3566,2024-10,125GX16 PAN0% PAN,4,0.000,4.590000,18.36,0.00,18.36
3738,2024-11,KIWI VERT PIECE,16,0.000,0.590000,9.44,-1.44,8.00
3669,2024-11,125G MOZZARELLA VA,6,0.000,0.990000,5.94,0.00,5.94
3704,2024-11,5X10 D FREEDENT WH,6,0.000,2.493333,14.96,-3.57,11.39
3735,2024-11,KAKI PIECE,6,0.000,0.690000,4.14,-1.14,3.00
3736,2024-11,KG TOMATE GRAP FR,6,7.425,2.906667,21.41,0.00,21.41
3820,2024-12,BOITE RANGT 30 L,11,0.000,11.990000,131.89,-66.00,65.89
3843,2024-12,KIWI VERT PIECE,11,0.000,0.640000,7.09,0.00,7.09
3822,2024-12,BQ TOM CERISE ALL,7,0.000,0.990000,6.93,0.00,6.93
3805,2024-12,6X1.5L EAU AUV CRF,6,0.000,1.620000,9.72,-0.32,9.40
3842,2024-12,KG TOMATE GRAP FR,6,6.054,3.090000,18.42,0.00,18.42

,yearMonth,productLabel,totalQuantity,totalWeight,unitPrice,totalPrice,totalImmediateDiscount,totalTruePrice
2453,2024-01,PDT CONSOMMATION,5,4.487,1.898000,10.46,0.0,10.46
2477,2024-01,TOMATE RDE CHARNUE,2,2.010,2.490000,5.27,0.0,5.27
2467,2024-01,POMME PINK LADY KG,2,1.744,1.990000,3.47,0.0,3.47
2451,2024-01,PATATE DOUCE VRAC,1,1.724,1.990000,3.43,0.0,3.43
2466,2024-01,POMME ARIANE VRAC,1,1.304,2.990000,3.90,0.0,3.90
2611,2024-02,PDT CONSOMMATION,2,2.854,1.990000,5.68,0.0,5.68
2590,2024-02,MANDARINE CRF,2,1.959,1.990000,3.90,0.0,3.90
2626,2024-02,POMME GRANNY GROSS,2,1.572,2.990000,4.70,0.0,4.70
2562,2024-02,CAROTTE VRAC,1,1.036,2.490000,2.58,0.0,2.58
2627,2024-02,POMME PINK LADY KG,1,0.915,1.990000,1.82,0.0,1.82
2783,2024-03,SAUMON ENTIER,2,4.904,11.990000,58.80,0.0,58.80
2757,2024-03,PDT CONSOMMATION,3,3.749,1.990000,7.46,0.0,7.46
2705,2024-03,BANANES,2,1.985,1.990000,3.95,0.0,3.95
2754,2024-03,PATATE DOUCE VRAC,2,1.807,2.490000,4.58,0.0,4.58
2737,2024-03,KG TOMATE GRAP FR,2,1.683,3.290000,5.63,0.0,5.63
2816,2024-04,CAROTTE VRAC,2,1.678,1.990000,3.34,0.0,3.34
2876,2024-04,Poulet jaune PAC Label Rouge FERMIERS DE LOUE,1,1.617,8.620000,9.30,0.0,9.30
2848,2024-04,KG TOMATE GRAP FR,1,1.251,1.990000,2.49,0.0,2.49
2863,2024-04,PDT CONSOMMATION,1,1.206,1.990000,2.40,0.0,2.40
2869,2024-04,POMME PINK LADY KG,1,0.799,3.490000,2.79,0.0,2.79
3000,2024-05,PDT CONSOMMATION,2,2.699,1.990000,5.37,0.0,5.37
2976,2024-05,KG TOMATE GRAP FR,4,2.428,2.165000,5.18,0.0,5.18
2952,2024-05,CAROTTE VRAC,2,1.689,1.990000,3.36,0.0,3.36
2956,2024-05,COURGETTE,2,1.631,1.990000,3.23,0.0,3.23
2941,2024-05,BANANES,1,1.171,1.990000,2.33,0.0,2.33
3079,2024-06,KG TOMATE GRAP FR,3,2.540,1.640000,4.54,0.0,4.54
3107,2024-06,POULET JAUNE LR LO,1,1.717,5.750000,9.87,0.0,9.87
3104,2024-06,POMME ARIANE VRAC,1,0.977,2.990000,2.92,0.0,2.92
3059,2024-06,CAROTTE FQC VRAC,1,0.764,1.990000,1.52,0.0,1.52
3077,2024-06,HARICOT COCO PLAT,1,0.642,3.990000,2.56,0.0,2.56
3222,2024-07,POULET JAUNE LR LO,0,3.318,9.890000,4.92,0.0,4.92
3197,2024-07,KG TOMATE GRAP FR,2,3.086,1.923333,5.80,0.0,5.80
3218,2024-07,POMM TERRE PRIMEUR,1,1.591,3.990000,6.35,0.0,6.35
3220,2024-07,POMME GRANNY VRAC,1,1.584,1.490000,2.36,0.0,2.36
3211,2024-07,PECHE PLATE VRAC,2,1.292,2.656667,3.08,0.0,3.08
3326,2024-08,KG TOMATE GRAP FR,2,3.483,2.240000,7.79,0.0,7.79
3306,2024-08,DAURADE ROYALE ELV,1,2.351,6.990000,16.43,0.0,16.43
3357,2024-08,PECHE PLATE VRAC,2,1.639,2.990000,4.90,0.0,4.90
3345,2024-08,NAVET MARTEAU KG,1,1.590,2.290000,3.64,0.0,3.64
3375,2024-08,Poulet jaune PAC Label Rouge FERMIERS DE LOUE,1,1.584,9.110000,9.11,0.0,9.11
3510,2024-09,KG TOMATE GRAP FR,5,6.258,1.950000,12.27,0.0,12.27
3496,2024-09,FILET SAUMON FQC A,2,5.268,11.990000,63.17,0.0,63.17
3517,2024-09,MAQUEREAU,1,2.790,6.490000,18.11,0.0,18.11
3485,2024-09,COURGETTE,2,2.248,1.640000,3.69,0.0,3.69
3490,2024-09,DAURADE ROYALE ELV,2,1.876,8.990000,16.87,0.0,16.87
3631,2024-10,KG TOMATE GRAP FR,4,4.997,2.740000,14.07,0.0,14.07
3652,2024-10,POULET JAUNE LR LO,2,3.931,5.500000,21.62,0.0,21.62
3603,2024-10,AUBERGINE VRAC,2,1.436,1.840000,2.53,0.0,2.53
3642,2024-10,NASHI,1,0.996,4.990000,4.97,0.0,4.97
3607,2024-10,BANANES,1,0.798,1.290000,1.03,0.0,1.03
3736,2024-11,KG TOMATE GRAP FR,6,7.425,2.906667,21.41,0.0,21.41
3761,2024-11,POMME TERRE STD,2,2.226,1.990000,4.43,0.0,4.43
3763,2024-11,SAUMON ENTIER,1,1.998,9.990000,19.96,0.0,19.96
3760,2024-11,POMME PINK LADY KG,2,1.855,3.090000,5.47,0.0,5.47
3762,2024-11,POULET JAUNE LR LO,1,1.718,5.500000,9.45,0.0,9.45
3842,2024-12,KG TOMATE GRAP FR,6,6.054,3.090000,18.42,0.0,18.42
3876,2024-12,SAUMON ENTIER,1,2.913,8.900000,25.93,0.0,25.93
3871,2024-12,POMME PINK LADY KG,2,1.975,2.340000,4.55,0.0,4.55
3825,2024-12,CAROTTE FQC VRAC,2,1.907,1.390000,2.68,0.0,2.68
3811,2024-12,AGN GIGOT***,1,1.778,10.890000,19.36,0.0,19.36

In [ ]:
# Group by year_month and product_id, then sum the quantities
grouped_year = df_prod.groupby(['year', 'productLabel']).agg(
    {'totalQuantity' : 'sum', 'totalWeight': 'sum', 'unitPrice' : 'mean', 'price' : 'sum', 'totalImmediateDiscount' : 'sum'}).reset_index()

# Sort by year_month and quantity in descending order
sorted_grouped_year_quant = grouped_year.sort_values(by=['year', 'totalQuantity'], ascending=[True, False])
sorted_grouped_year_weight = grouped_year.sort_values(by=['year', 'totalWeight'], ascending=[True, False])

# Get the top 10 items for each month
top10_quant_by_year = sorted_grouped_year_quant.groupby('year').head(10)  # Top N records per group
top10_weight_by_year = sorted_grouped_year_weight.groupby('year').head(10)  # Top N records per group
display(top10_quant_by_year)
display(top10_weight_by_year)

,year,name,totalQuantity,totalWeight,unitPrice,price,immediateDiscount
447,2022,KIWI PIECE,129,0.000,0.564000,4.893333,-0.390000
51,2022,16X125 VELOUTE NAT,19,0.000,3.778750,3.778750,0.000000
356,2022,CHAUSSON AUX POMME,18,0.000,0.750000,1.934000,0.000000
291,2022,AVOCAT PIECE,16,0.000,1.170000,3.888000,-0.266000
372,2022,CONCOMBRE PIECE,16,0.000,1.111250,2.222500,-0.022500
614,2022,VIENNOISERIE AUX A,16,0.000,0.755000,3.020000,0.000000
467,2022,MANGUE PIECE,14,0.000,1.484000,3.022000,-0.324000
290,2022,AUBERGINE VIOLETTE,13,6.118,2.860769,1.358462,0.000000
336,2022,BT 3X110MOUCH.CONF,13,0.000,3.475714,3.475714,-0.158214
485,2022,NESCAFE SPEC.FILTR,13,0.000,6.120833,6.120833,-0.050000
1222,2023,KIWI PIECE,143,0.000,0.579474,3.598684,-0.275789
1223,2023,KIWI VERT PIECE,87,0.000,0.591818,4.751818,-0.690909
1038,2023,AVOCAT PIECE,47,0.000,1.215833,4.284167,-0.199167
981,2023,6X1.5L CRISTALINE,43,0.000,1.140000,1.915200,0.000000
1087,2023,BT 3X110MOUCH.CONF,36,0.000,3.745455,3.745455,-0.328182
1431,2023,TOMATE CERISE ALL.,33,0.000,0.990000,1.089000,0.000000
1130,2023,CONCOMBRE PIECE,26,0.000,1.175333,1.739778,-0.053333
707,2023,16X125 VELOUTE NAT,22,0.000,4.358182,4.358182,0.000000
1288,2023,PAIN AUX RAISINSX1,18,0.000,0.750000,2.250000,0.000000
1338,2023,POIREAU VRAC,16,8.099,2.287500,1.163333,0.000000
2031,2024,KIWI VERT PIECE,164,0.000,0.594583,4.043333,-0.577917
1924,2024,CHEM 3RBT POLYPRO,40,0.000,1.190000,11.900000,0.000000
2026,2024,KG TOMATE GRAP FR,36,39.731,2.540000,2.719583,0.000000
1895,2024,BQ TOM CERISE ALL,32,0.000,0.990000,1.056000,0.000000
1856,2024,AVOCAT PIECE,31,0.000,1.283077,2.743077,-0.249231
1801,2024,6X1.5L CRISTALINE,28,0.000,1.140000,1.995000,0.000000
1941,2024,CONCOMBRE PIECE,28,0.000,1.100000,1.706471,-0.125294
1632,2024,24 PS EXTRA LONG C,24,0.000,1.550000,2.131250,-0.106563
2305,2024,X5 CHEM 3R CTE CRF,21,0.000,2.990000,62.790000,0.000000
1865,2024,BATAVIA PIECE,20,0.000,1.105789,1.105789,-0.004737
2536,2025,KIWI VERT PIECE,42,0.000,0.604286,3.668571,-0.631429
2485,2025,BQ TOM CERISE ALL,18,0.000,0.990000,0.990000,0.000000
2333,2025,125GX16 PAN0% PAN,14,0.000,4.590000,4.590000,-0.114583
2535,2025,KIWI VERT FQC,14,0.000,0.590000,2.753333,0.000000
2469,2025,BANANE CRF BIO,13,0.000,1.990000,1.990000,-0.050000
2473,2025,BATAVIA PIECE,11,0.000,1.362727,1.362727,0.000000
2465,2025,AVOCAT PIECE,9,0.000,1.330000,1.568000,-0.076000
2488,2025,BT 3X110MOUCH.CONF,9,0.000,3.730000,3.730000,-0.365000
2395,2025,3.0 CHATAIN FONCE,8,0.000,9.280000,9.280000,-2.783750
2464,2025,AUBERGINE VRAC,7,5.088,2.532857,1.730000,0.000000

,year,name,totalQuantity,totalWeight,unitPrice,price,immediateDiscount
603,2022,TOMATE GRAPPE FRAN,8,10.050,2.365000,2.932500,0.0
290,2022,AUBERGINE VIOLETTE,13,6.118,2.860769,1.358462,0.0
544,2022,POMME GRANNY GROSS,7,5.184,2.442857,1.822857,0.0
512,2022,PDT CONSERVATION,4,4.685,1.690000,2.020000,0.0
548,2022,PORC SAUTE EPAULE,5,4.422,6.120000,4.865000,0.0
546,2022,POMME PINK LADY,4,4.348,3.590000,3.937500,0.0
376,2022,COURGETTE,5,4.223,2.650000,2.176000,0.0
299,2022,BANANE OPEN TOP VR,3,3.539,1.690000,1.993333,0.0
596,2022,TARO VRAC,4,3.513,6.640000,5.902500,0.0
543,2022,POMME GALA MOYENNE,3,3.293,2.390000,2.827500,0.0
1433,2023,TOMATE GRAPPE FRAN,15,13.633,2.390000,2.285333,0.0
1304,2023,PDT CONSERVATION,10,11.071,1.861000,2.050000,0.0
1397,2023,SAUMON ENTIER,4,10.938,9.990000,26.933333,0.0
1338,2023,POIREAU VRAC,16,8.099,2.287500,1.163333,0.0
1152,2023,DAURADE ROYALE ELV,6,6.436,8.546667,10.236667,0.0
1136,2023,COURGETTE,9,6.280,2.056667,1.607778,0.0
1336,2023,POIRE CONFERENCE,7,5.392,2.847143,2.198571,0.0
1337,2023,POIRE CONFERENCE M,7,4.996,2.932857,2.031429,0.0
1106,2023,CAROTTE FQC VRAC,7,4.957,1.955714,1.372857,0.0
1435,2023,TOMATE GRAPPE VRAC,6,4.937,2.840000,2.421667,0.0
2026,2024,KG TOMATE GRAP FR,36,39.731,2.540000,2.719583,0.0
2138,2024,PDT CONSOMMATION,15,17.382,1.959333,2.408000,0.0
2208,2024,POULET JAUNE LR LO,5,11.905,6.315000,8.403333,0.0
2243,2024,SAUMON ENTIER,4,9.815,10.293333,25.096667,0.0
1913,2024,CAROTTE FQC VRAC,14,9.303,1.797857,1.169286,0.0
2200,2024,POMME PINK LADY KG,10,9.119,2.530000,2.280000,0.0
1914,2024,CAROTTE VRAC,8,7.247,1.990000,1.793750,0.0
1943,2024,COURGETTE,8,6.826,2.001111,1.507778,0.0
1854,2024,AUBERGINE VRAC,9,6.788,2.634444,2.041111,0.0
2127,2024,PATATE DOUCE VRAC,6,5.793,2.223333,2.151667,0.0
2588,2025,POULET JAUNE LR LO,5,7.770,6.590000,9.668000,0.0
2534,2025,KG TOMATE GRAP FR,6,7.315,3.456667,4.148333,0.0
2604,2025,TOMATE GRAPPE,5,5.540,3.210000,3.536000,0.0
2492,2025,CAROTTE FQC VRAC,6,5.105,1.540000,1.231667,0.0
2464,2025,AUBERGINE VRAC,7,5.088,2.532857,1.730000,0.0
2541,2025,MANDARINE VRAC AU,5,4.453,2.710000,2.356000,0.0
2493,2025,CAROTTE VRAC,4,3.426,1.690000,1.452500,0.0
2582,2025,POMME GALA FQC,3,3.409,2.123333,2.426667,0.0
2519,2025,FILET SAUMON FQC A,2,3.300,18.990000,31.330000,0.0
2586,2025,POMME TERRE STD,3,2.598,1.990000,1.723333,0.0

# Partial string matching

Thanks to the grouping analysis, we get a grasp of the top products on which we want to make further analysis like actual price evolutions, purchased quantities, variations of item types, etc.

We use regular expressions as well `str.contains()` and fuzzy matching thanks to `rapidfuzz` (for scalability sake).

For each date we have a matching products. In order to perform good matching, we should need to preprocess the labels as to have the dates as tokens that helps to do the matching.

Use `sentence_transformers` for embeddings and compute cosine similarity. For uncertain ones (similarity scores < 0.5), do some normal fuzzy ratio stuff and voting first, second best match and best fuzzy match (based of substring matching rather than contextual matching).

We use Roberta model which is intermediate in terms of performance as the base model is quite lacking on sample analysis.
https://sbert.net/docs/sentence_transformer/pretrained_models.html

In [24]:
def preprocess(text: str): 
    text = text.lower()
    # Normalize to decomposed form (split base characters and diacritics)
    nfkd_form = unicodedata.normalize('NFKD', text)
    text = u"".join([c for c in nfkd_form if not unicodedata.combining(c)])
    
    # Use regex to remove diacritics (Mn = Mark, Nonspacing)
    # text = re.sub(r'\p{Mn}', '', text, flags=re.UNICODE)
    # text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    return text.strip()

def fuzzy_match(row, choices, scorer=fuzz.WRatio, processor=None, threshold=80):
    """
    Perform fuzzy matching for a single row against a list of choices based on date criterion.
    Returns the best match and its score if above the threshold.
    """
    result = process.extractOne(row, choices, scorer=scorer, processor=processor, score_cutoff=threshold)
    return result[0] if result is not None else None

In [25]:
def embedding_to_df(
    model,
    df: pd.DataFrame,
    column_name: str,
    new_column_name: str = "embeddingLabel",
    filter_out: str | None = None,
    filter_in: str | None = None
):
    """In-place computation of embedding"""
    if filter_in:
        mask = (df[column_name].notna()) & (df[column_name].str.contains(filter_in))
        df.loc[mask, new_column_name] = df.loc[mask, column_name].apply(
            lambda x: get_cached_encode(model, x)
        )
    else:
        if filter_out:
            mask = (df[column_name].isna()) | (df[column_name].str.contains(filter_out))
        else:
            mask = df[column_name].isna()
        df.loc[~mask, new_column_name] = df.loc[~mask, column_name].apply(
            lambda x: get_cached_encode(model, x)
        )


# Define a cached version of the embedding function
def get_cached_encode(model, text):
    @lru_cache(maxsize=None)  # Cache all results
    def cached_encode(text):
        return model.encode(preprocess(text))
    return cached_encode(text)


def match_labels_df(
    df1: pd.DataFrame, df2: pd.DataFrame, params: Dict[str, Any], criterion: str | None = None
) -> None:
    """Matching names in columns of DataFrames
    Args:
        df1 : with new col
    """
    required_params = ["col1", "col2", "newCol", "groupby1", "groupby2"]
    for param in params.keys():
        if param not in required_params:
            raise KeyError(f"Missing required parameter: {param}")
    # Group rows by date
    grouped_df1 = df1[df1[params["newCol"]].notna()].groupby(params["groupby1"])
    if criterion:
        grouped_df2 = df2[(df2[params["newCol"]].notna()) & (df2[params["col2"]].str.contains(criterion))].groupby(params["groupby2"])
    else:
        grouped_df2 = df2[df2[params["newCol"]].notna()].groupby(params["groupby2"])

    # Iterate over unique dates in df1
    for date, group1 in grouped_df1:
        # group1 = group1.reset_index(drop=True)

        if date in grouped_df2.groups:
            group2 = grouped_df2.get_group(date)
            group2 = group2.reset_index(drop=True)

            # Compute pairwise cosine similarity between embeddings
            similarity_matrix = cosine_similarity(
                np.vstack(group1[params["newCol"]]), np.vstack(group2[params["newCol"]])
            )
            idx = 0
            # Find the best match for each row in group1
            for i, row1 in group1.iterrows():
                # best_match_idx = np.argmax(similarity_matrix[i])

                sort_indices = np.argsort(similarity_matrix[idx])[::-1]
                best_match = group2.iloc[sort_indices[0]]
                similarity_score = similarity_matrix[idx][sort_indices[0]]
                df1.at[i, "matchedLabel1"] = best_match[params["col2"]]
                df1.at[i, "similarity_score1"] = similarity_score

                df1.at[i, "matchedLabelFuzzy"] = fuzzy_match(
                    row1[params["col1"]],
                    choices=group2[params["col2"]].unique(),
                    scorer=fuzz.WRatio,
                    processor=preprocess,
                )

                # Second-best match (if it exists)
                if len(sort_indices) > 1:
                    second_best_match = group2.iloc[sort_indices[1]]
                    df1.at[i, "matchedLabel2"] = second_best_match[params["col2"]]
                    df1.at[i, "similarity_score2"] = similarity_matrix[idx][
                        sort_indices[1]
                    ]
                idx += 1

def last_mode(row):
    modes = row.mode()
    if len(modes) > 1:
        return row.iloc[-1] if row.iloc[-1] else row.iloc[0]
    else:
        return modes.iloc[0]

In [26]:
# Load a pre-trained Sentence Transformer model
# model = SentenceTransformer("all-MiniLM-L6-v2")
model = SentenceTransformer('all-distilroberta-v1') # better model slightly but longer to process

In [27]:
# embedding_to_df(model, df_loyalty, 'itemLabel')
# embedding_to_df(model, df_prod, 'productLabel')
params = {
    "col1" : "itemLabel", 
    "col2" : "productLabel", 
    "newCol" : "embeddingLabel", 
    "groupby1" : "date", 
    "groupby2" : "dateKey"
}
embedding_to_df(
    model,
    df_loyalty,
    params["col1"],
    new_column_name="embeddingLabel",
    filter_out="ART RAYON",
)
embedding_to_df(model, df_prod, params["col2"])

In [28]:
match_labels_df(df_loyalty, df_prod, params)

In [29]:
df_loyalty.loc[df_loyalty.similarity_score1 > 0.5, "matchedLabel"] = df_loyalty.loc[
    df_loyalty.similarity_score1 > 0.5, "matchedLabel1"
]
df_loyalty.loc[df_loyalty.similarity_score1 <= 0.5, "matchedLabel"] = df_loyalty.loc[
    df_loyalty.similarity_score1 <= 0.5,
    ["matchedLabel1", "matchedLabel2", "matchedLabelFuzzy"],
].apply(last_mode, axis=1)

In [31]:
df_loyalty

,operationId,date,earned,burned,itemLabel,promotionLabel,itemRd,loyaltyOperation,embeddingLabel,matchedLabel1,similarity_score1,matchedLabelFuzzy,matchedLabel2,similarity_score2,matchedLabel
0,64070450536,2024-09-28,0.66,0.00,20 OEUFS DJP POULE AU SOL CRF,NaN,0.46,Paiement en caisse,"[0.008895143, 0.002929899, 0.030979047, -0.053...",20 OEUFS DJP POULE,0.857691,20 OEUFS DJP POULE,350G OIGN SAUCIER,0.437943,20 OEUFS DJP POULE
1,64070450536,2024-09-28,0.66,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en caisse,"[-0.0008011513, 0.018176839, 0.0037206716, 0.0...",BANANE CRF BIO,0.745447,BANANE CRF BIO,PCE BROCOLI FQC F,0.374859,BANANE CRF BIO
2,64063052302,2024-09-24,0.30,0.00,1KG COUSCOUS MOYEN CRF,NaN,0.30,Paiement en caisse,"[-0.0013854598, -0.046837345, 0.00067186187, -...",1KG COUSCOUS MOYEN,0.921145,1KG COUSCOUS MOYEN,190G PESTO ROQUE-B,0.492827,1KG COUSCOUS MOYEN
3,64072667140,2024-09-20,0.20,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.20,Paiement en ligne,"[-0.0008011513, 0.018176839, 0.0037206716, 0.0...",Bananes Bio CARREFOUR BIO,0.678154,Yaourt aux fruits jaunes pêche abricot poire a...,Yaourt aux fruits jaunes pêche abricot poire a...,0.477828,Bananes Bio CARREFOUR BIO
4,64073135027,2024-09-13,0.00,-22.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,65151220627,2025-03-08,21.30,0.00,"ART RAYON FRUITS LEG TVA 5,5",NaN,1.29,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,65151220627,2025-03-08,21.30,0.00,"ART RAYON POISSONNERIE TVA 5,5",NaN,12.91,Paiement en caisse,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,65151220627,2025-03-08,21.30,0.00,CHOU FLEUR PIECE,NaN,0.26,Paiement en caisse,"[-0.0059086564, -0.05829449, 0.0066939592, -0....",CHOU FLEUR PIECE,1.000000,CHOU FLEUR PIECE,1L HUILE FLEUR DE,0.558918,CHOU FLEUR PIECE
332,65151220627,2025-03-08,21.30,0.00,BANANE CRF BIO MH 5 FRUITS,NaN,0.25,Paiement en caisse,"[-0.0008011513, 0.018176839, 0.0037206716, 0.0...",BANANE CRF BIO,0.745447,BANANE CRF BIO,125GX8 PAN0% JNES,0.318713,BANANE CRF BIO
333,65155914438,2025-03-05,19.90,0.00,NaN,Retrouvez le détail de vos avantages dans la r...,NaN,Avantages exceptionnels,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df_loyalty.to_csv('data/20250501-carrefour_loyalty_extended.csv', index=False)

In [ ]:
# embedding_to_df(
#     model,
#     df_loyalty,
#     "itemLabel",
#     new_column_name="embeddingLabel",
#     filter_out=None,
#     filter_in="ART RAYON",
# )

In [ ]:
# params_other = {
#     "col1" : "productLabel", 
#     "col2" : "itemLabel", 
#     "newCol" : "embeddingLabel", 
#     "groupby1" : "dateKey", 
#     "groupby2" : "date"
# }

# match_labels_df(df_prod, df_loyalty, params_other, criterion='ART RAYON')

In [46]:
df_loyalty.query("(itemLabel.notna()) & (itemLabel.str.contains('ART RAYON'))").value_counts(["itemLabel"])

itemLabel
ART RAYON FRUITS LEG TVA 5,5      23
ART RAYON POISSONNERIE TVA 5,5     8
ART RAYON BOUCHERIE TVA 5,5        4
Name: count, dtype: int64

In [63]:
df_prod.query("(matchedLabel1.notna()) & (matchedLabel1.str.contains('ART RAYON')) & (category == 'food')")[['productLabel', 'category', 'subCategory']].value_counts(["productLabel", "subCategory"])

productLabel                                    subCategory
Blanc de dinde fumé FLEURY MICHON               Charcuterie                          1
Chips au Comté BRET'S                           Apéritifs et Chips                   1
Chips saveur cheeseburger LAY'S                 Apéritifs et Chips                   1
Coulommiers Savoureux Et Crémeux PRESIDENT      Fromages                             1
Eau de source CRISTALINE                        Eaux                                 1
Huile de pépins de raisin CARREFOUR CLASSIC'    Huiles, Vinaigres et Vinaigrettes    1
Maïs sans sucres ajoutés CARREFOUR CLASSIC'     Repas de Pâques                      1
Nectar fruit de la passion CARREFOUR SELECTION  Jus de fruits et légumes             1
Name: count, dtype: int64

Given the results, let us determine appropriate thresholds for which we get the matched labels are retained. For matched label with low similarity score, let us say the bottom 10%, we may want to have a vote with the second match and fuzzy.

Naturally, we want a threshold at 0.5, but it is not based on any kind of statistical property. It is kind of practical.

# Categorization

We want to know how many tomatoes we consume or how many detergent we use by year for example. This requires categorization.

In [ ]:
categories = {
    'Tomate' : ['Tomate Cerise', 'Tomate Grappe'],
    'Lessive' : ['ARIEL', 'XTRA'],
    'Nettoyants vaisselle' : ['PAIC', 'MIR'],
    'Papier toilette' : ['Papier toilette'], 
    'Mouchoirs' : ['Mouchoirs'], 
    'Légumes verts' : ['Céleri', 'Poireau', 'BATAVIA'],
    'Légumes non verts' : ['Courgette', 'Aubergine', 'Poivrons', 'Piment', 'Concombre']
}

In [ ]:
df_prod.query("(matchedLabel1.notna()) & (matchedLabel1.str.contains('ART RAYON')) & (category == 'food') & (recordType == 'receipt')")[['productLabel', 'category', 'subCategory']].drop_duplicates('productLabel').to_csv(path_or_buf='data/20250502-carrefour_food_products.csv', index=False)

In [6]:
df_prod.query("((category == 'food') & (recordType == 'order'))")[['productLabel', 'category', 'subCategory']].drop_duplicates('productLabel').to_csv(path_or_buf='data/20250502-carrefour_food_order_products.csv', index=False)

In [ ]:
df_prod.query(
    "productLabel.str.contains('tomate', case=False) & totalWeight > 0"
).value_counts(["recordType", "productLabel", "unitPrice"])